### ISSUE TITLE
数据集咨询

### ISSUE THREAD

**Issue by jiayidengYumy** [masr2000/CLG-CGEC#3]
您好，我想请问一下就是这个nlpcc2023年度的数据集在哪里下载呢，应该也就是这篇论文的数据集，非常感谢！

**Comment by masr2000** [comment]
感谢您的关注！nlpcc2023 shared task 1的guideline和相关数据我还在做最后检查，预计今天将会按照nlpcc官方的流程发布到nlpcc的官网。
