### ISSUE TITLE
测试数据集NaCGEC

### ISSUE THREAD

**Issue by zxyucas** [masr2000/CLG-CGEC#6]
为什么测试数据集NaCGEC论文中的数据量与比赛中的数据量对应不上？

**Comment by masr2000** [comment]
您好，感谢您对我们工作的关注。在比赛开始前我们对相关的数据进行了再次检查和优化，具体细节烦请以比赛发布数据为准。对由此给您带来的困惑表示抱歉。

**Comment by zxyucas** [comment]
那可以从测试集中分出EXAM数据集吗
